openapi: 3.0.0
info:
  title: Project 2 CRUD API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/authors:
    get:
      summary: Get list of authors
      responses:
        "200":
          description: OK
    post:
      summary: Create an author
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
      responses:
        "201":
          description: Created
  /api/authors/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get author by id
      responses:
        "200":
          description: OK
    put:
      summary: Update an author
      responses:
        "200":
          description: OK
    delete:
      summary: Delete an author
      responses:
        "200":
          description: Deleted
  /api/books:
    get:
      summary: Get list of books
      responses:
        "200":
          description: OK
    post:
      summary: Create a book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                isbn:
                  type: string
                author:
                  type: string
      responses:
        "201":
          description: Created
  /api/books/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a book by id
      responses:
        "200":
          description: OK
    put:
      summary: Update a book
      responses:
        "200":
          description: OK
    delete:
      summary: Delete a book
      responses:
        "200":
          description: Deleted
